default: &default
  url: <%= ENV["REDIS_URL"] %>

development:
  adapter: redis
  <<: *default

test:
  adapter: test
  <<: *default

production:
  adapter: redis
  <<: *default
  channel_prefix: hackernews_top_15_production
